### ISSUE TITLE
[FEATURE] Add VPN module to waybar

### ISSUE THREAD

**Issue by pendula95** [mylinuxforwork/dotfiles#330]
I have made a little waybar module that shows VPN connection status.
If this is something you think is useful you can add it as optional module to waybar.

modules config:
```js
  "custom/vpn": {
    "format": "{icon}   vpn",
    "exec": "~/.config/custom/scripts/waybar-vpn.sh",
    "interval": 5,
    "tooltip": true,
    "return-type": "json",
    "format-icons" : {
        "active": "",
        "inactive": ""
    }
  }
```

custom script:
  ```sh
#!/bin/bash

# Get VPN information
vpn_info=$(nmcli c show --active | grep -w "vpn")

# Check if VPN is active
if [ -n "$vpn_info" ]; then
    # Extract VPN name and interface
    vpn_name=$(echo "$vpn_info" | awk '{print $1}')
    vpn_interface=$(echo "$vpn_info" | awk '{print $NF}')
    
    # Output for Waybar to use format-icons "vpn-active"
    echo "{\"name\": \"$vpn_name\", \"tooltip\": \"VPN: $vpn_name\nInterface: $vpn_interface\", \"alt\": \"active\"}"
else
    # Output for Waybar to use format-icons "vpn-inactive"
    echo "{\"tooltip\": \"No VPN connection active\", \"alt\": \"inactive\"}"
fi
```

style:
```css
#custom-vpn {
    background-color: @backgroundlight;
    font-size: 16px;
    color: @textcolor2;
    border-radius: 15px;
    padding: 2px 10px 0px 10px;
    margin: 8px 15px 8px 0px;
    opacity:0.8;
}
```

And ofc add it to config `"custom/vpn"`
![image](https://github.com/user-attachments/assets/74dd5478-24c5-44b9-a509-aedede135803)
![image](https://github.com/user-attachments/assets/1898677c-7c6f-4679-8cb7-ffc4ae2fc050)
